import type { SectionLayout, SectionType } from '../types';

/** Classic preset — mirrors the original hardcoded look for each section type. */
export const classicLayouts: Record<SectionType, SectionLayout> = {
  summary: {
    presetId: 'classic',
    dateSlot: 'hidden',
    iconStyle: 'none',
    separator: 'none',
    density: 'compact',
    columns: 1,
    showTitleRule: false,
  },
  education: {
    presetId: 'classic',
    dateSlot: 'right-inline',
    iconStyle: 'none',
    separator: 'none',
    density: 'compact',
    columns: 1,
    showTitleRule: false,
  },
  skills: {
    presetId: 'classic',
    dateSlot: 'hidden',
    iconStyle: 'none',
    separator: 'none',
    density: 'compact',
    columns: 1,
    showTitleRule: false,
  },
  certifications: {
    presetId: 'classic',
    dateSlot: 'right-inline',
    iconStyle: 'none',
    separator: 'none',
    density: 'compact',
    columns: 1,
    showTitleRule: false,
  },
  projects: {
    presetId: 'classic',
    dateSlot: 'hidden',
    iconStyle: 'bullet',
    separator: 'none',
    density: 'relaxed',
    columns: 1,
    showTitleRule: false,
  },
  awards: {
    presetId: 'classic',
    dateSlot: 'right-inline',
    iconStyle: 'none',
    separator: 'none',
    density: 'compact',
    columns: 1,
    showTitleRule: false,
  },
  volunteering: {
    presetId: 'classic',
    dateSlot: 'right-inline',
    iconStyle: 'none',
    separator: 'none',
    density: 'compact',
    columns: 1,
    showTitleRule: false,
  },
  'work-experience': {
    presetId: 'classic',
    dateSlot: 'right-inline',
    iconStyle: 'bullet',
    separator: 'none',
    density: 'compact',
    columns: 1,
    showTitleRule: false,
  },
  custom: {
    presetId: 'classic',
    dateSlot: 'hidden',
    iconStyle: 'none',
    separator: 'none',
    density: 'compact',
    columns: 1,
    showTitleRule: false,
  },
};
